#!/usr/bin/env bash

TOOLBOX_HOOKS_SSH=${TOOLBOX_HOOKS_SSH-false}

if [ "${TOOLBOX_HOOKS_SSH}" == "true" ]; then
  if [ "${TOOLBOX_LOG_LEVEL}" = "TRACE" ]; then set -x; fi

  if [ -f toolbox/.secrets/id_rsa ]; then
    rm -f toolbox/.tmp/mounts/root/.ssh/id_rsa

    toolbox_run "Hook :: ${1} :: ${2} :: Copy id_rsa key into toolbox/.tmp/mounts/root/.ssh/ before mounting" \
      cp toolbox/.secrets/id_rsa toolbox/.tmp/mounts/root/.ssh/

    chmod 400 toolbox/.tmp/mounts/root/.ssh/id_rsa
  fi

  if [ -f "${TOOLBOX_DOCKER_MOUNTS_DIR}"/root/.ssh/config ]; then
    chmod 600 toolbox/.tmp/mounts/root/.ssh/config
  fi

  if [ "${TOOLBOX_DOCKER_CONTEXT}" = "DOCKER" ] && [ "${TOOLBOX_DOCKER_MODE}" = "DIND" ]; then
    chown -R root:root toolbox/.tmp/mounts/root/.ssh; \
  fi;

  if [ "${TOOLBOX_LOG_LEVEL}" = "TRACE" ]; then set +x; fi
else
  _log DEBUG "TOOLBOX_HOOKS_SSH=false, hook is not executed"
fi
